
# This file was automatically created from localization JSON files.
# DO NOT EDIT THIS FILE DIRECTLY. If you want to edit a translation, please use the language's JSON file.

from typing import Literal, List
Language=Literal['en']
languages: List[Language] = ['en']
default_lang: Language | str='en'
def change_language(new_lang: Language | str) -> None: global default_lang; default_lang = new_lang
def mode_is_invalid(mode,lang:str|None=None):
	"""{mode} is not a valid mode. Please ensure that your config.json file is properly set up."""
	if not lang: lang=default_lang
	if lang == "en": return "{mode} is not a valid mode. Please ensure that your config.json file is properly set up.".format_map({"mode": mode})
	else: raise ValueError(f'Invalid language {lang}')
def unexpected_error(lang:str|None=None):
	"""ERROR: An unexpected error occurred:"""
	if not lang: lang=default_lang
	if lang == "en": return "ERROR: An unexpected error occurred:"
	else: raise ValueError(f'Invalid language {lang}')
